---
title: "Data Tidying and Reporting – Task 1"
author: "Gabriela Levenfeld Sabau"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: false
    number_sections: false
    highlight: tango
    latex_engine: xelatex
    fig_caption: true
    extra_dependencies:
      - geometry
bibliography: references.bib
nocite: '@*'
link-citations: yes
linkcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.bg = 'transparent')
```

## Introduction

Handwritten digit recognition involves the conversion of human handwritten digit images into digital representations [[Ref. 1]](https://learner-cares.medium.com/handwritten-digit-recognition-using-convolutional-neural-network-cnn-with-tensorflow-2f444e6c4c31). This task might be challenging due to humans imperfections and the wide variability of handwritten forms.

The dataset used for this project has been provided by the professor in the file named `qmnist_nist.RData`. It contains both the training and testing datasets, storing the images as collections of pixel values. This report focuses on using ridge logistic regression to distinguish between handwritten digits, specifically $4$ and $9$, providing insights into the digit classification.

*Write reference correctly*

## Methodology

Ridge logistic regression is a regularization technique used to classify data by applying a penalty term to the logistic regression loss function. The penalty term, represented by $\lambda\sum_{j=1}^n \beta_j^2$, helps shrink the coefficients towards zero, effectively limiting the model's complexity and reducing overfitting. The main advantage is that this technique is well-suited for high-dimensional data like images.

1.  **Data preparation**. This step must be performance on both the training and testing dataset. The data is filtered to only include digits $4$ and $9$, which are the numbers we want to learn to classify. Then, the data is transformed into a suitable format in order to use the model.

2.  **Model training**. It is implemented using the `glmnet` package.
Cross-validation is employed to determine the optimal $\lambda$ (*Explain why is it useful*), which controls the strength of regularization. The predictors are not standardized due to the consistent scale and range of pixel values in handwritten digit images.

3.  **Model performance**. The model's performance has been assessed using the test set, a separate data not used up to now. The evaluation metric is based on the proportion of correctly classified digits, known as accuracy.

## Results

-   **Training**. During this step, we can get some insights about the $\beta$ parameters of the model. The following plot shows the magnitude and direction of the coefficients, indicating which pixels contribute more to the classification of digits $4$ and $9$. Larger magnitude coefficients means higher contribution. 

-   **Testing**. The model achieved an accuracy of *poner valor linkeado a la variable*, which demonstrated a remarkable ability to differentiate between this two digits.

## Conclusion

## References

Poner *references* del paper y de los paquetes usados.

<div id="refs"></div>
